# syntax=docker/dockerfile:1
FROM golang:1.24 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/tubo ./cmd/tubo

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/tubo /usr/local/bin/tubo
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/tubo"]
